name: dice_roller
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/dice/dice-1.png
    - assets/images/dice/dice-2.png
    - assets/images/dice/dice-3.png
    - assets/images/dice/dice-4.png
    - assets/images/dice/dice-5.png
    - assets/images/dice/dice-6.png